### ISSUE TITLE
Question : Where's productsEasyAccess documentation ?

### ISSUE THREAD

**Issue by BebZ** [lrq3000/dolibarr_customfields#3]
I have seen one day a website (surely yours) that has a documentation about it to generate lists of products in odt (i think it was with a product : red dress). 
I am quite sure it's related to your module, but now i can't find any website or copy of this website in cache...
(I remember it had a paypal button to buy the module)

**Comment by lrq3000** [comment]
Yes indeed the module ProductsEasyAccess is now merged in the CustomFields repository (here). The documentation is included within:

https://htmlpreview.github.io/?https://raw.githubusercontent.com/lrq3000/dolibarr_customfields/pro/htdocs/productseasyaccess/README.html

You can try to use it now but I'm not sure if it works with the latest Dolibarr versions.

**Comment by lrq3000** [comment]
It now works with latest Dolibarr versions, except for the barcodes.

**Comment by lrq3000** [comment]
#4

**Comment by lrq3000** [comment]
Barcodes also work now. PEA was updated to work with Dolibarr v3.9.1.
