### ISSUE TITLE
ProductsEasyAccess: barcode not working

### ISSUE THREAD

**Issue by lrq3000** [lrq3000/dolibarr_customfields#4]
Since at least Dolibarr 3.8.0 the barcodes cannot be displayed anymore using ProductsEasyAccess. This is because the default barcode class, as well as the layout of the barcode folder, has changed. Thus the code that is using PEA to automatically discover and load barcode plugins does not work anymore.

To make this work again, we would need to (almost) completely rewrite the part of the code that is discovering barcode classes. I don't know anything about the new layout and I couldn't understand the logic by reading the sourcecode (but I haven't spent too much time), so if anyone has any info on this, please feedback, this would help me to fix this issue.

**Comment by lrq3000** [comment]
#4

**Comment by BebZ** [comment]
@fappels wrote some tcpdf barcodes library or implemented maybe ?

**Comment by lrq3000** [comment]
Apparently people reported that it works now with Dolibarr 3.9.1 (maybe because I fixed something else). Closing this issue for now.
